version: 2
jobs:
  publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Check Tagged Push
          command: |
            TAG_VERSION=$(git describe --tags --candidates=1)
            PKG_VERSION=$(cat fluent-plugin-logdna.gemspec | grep s.version | cut -d \' -f2 | cut -d'.' -f1 -f2 -f3)
            if [[ "${TAG_VERSION}" != "${PKG_VERSION}" ]]; then
              echo "There is mismatch:"
              echo "  TAG_VERSION: ${TAG_VERSION}"
              echo "  PKG_VERSION: ${PKG_VERSION}"
              exit 1
            fi
      - run:
          name: Publish
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            npm publish
workflows:
  version: 2
  update_package:
    jobs:
      - publish:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+(\.[0-9]+)?/
            branches:
              ignore: /.*/
